
# mongo
# bash: docker-compose exec mongo-db bash
# to build and use latest jar: docker-compose up --build
version: "3.0"
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./job-service/src/test/resources/static:/docker-entrypoint-initdb.d
  job-service:
    build:
      context: .
      dockerfile: job-service/src/main/resources/Dockerfile
    image: job-service
    container_name: job-service
    depends_on:
      - mongo-db
    ports:
      - "8080:8080"
    environment:
      MONGO_DB_HOST: mongo-db
      MONGO_DB_PORT: 27017
      MONGO_DB_USERNAME: usr1
      MONGO_DB_PASSWORD: pwd1
      MONGO_DB_NAME: job
    # with profile -> docker-compose up -> only mongo-db will be running
    # to run both: docker-compose --profile=test up
    # useful when have different dbs
#    profiles:
#      - test