
spring:
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}
      username: ${MONGO_DB_USERNAME:usr1}
      password: ${MONGO_DB_PASSWORD:pwd1}
      database: ${MONGO_DB_NAME:job}