
spring:
  data:
    mongodb:
      host: ${MONGODB_JOB_HOST:localhost}
      port: ${MONGODB_JOB_PORT:27017}
      username: ${MONGODB_JOB_USERNAME:usr1}
      password: ${MONGODB_JOB_PASSWORD:pwd1}
      database: ${MONGODB_JOB_NAME:job}